### ISSUE TITLE
There are many structs you cannot see documentation for on docs.rs

### ISSUE THREAD

**Issue by Ploppz** [hecrj/iced#732] opened 2021-02-07 08:54 UTC
For example https://docs.rs/iced/0.2.0/iced/type.Element.html
Docs provide no information at all about this important type.
Not sure why it is so and what it takes to fix it.

**Comment by samyak-jain** [comment] 2021-02-08 20:34
Looks like a duplicate of this issue https://github.com/hecrj/iced/issues/340

You can find the actual element docs here: https://docs.rs/iced_native/0.3.0/iced_native/struct.Element.html

**Closed** 2021-02-12 21:02 UTC
Labels: duplicate
