### ISSUE TITLE
Text cut off when printing specific string

### ISSUE THREAD

**Issue by AZon8** [hecrj/iced#1015] opened 2021-08-30 12:24 UTC
Well... have fun with this one, because whatever diagnosis i can think up seems implausible. 
Don't have time to make a minimal example, but figured i'd at least make an issue just in case its an unhandeld edge case. 

Running on a wgpu_hal::vulkan on the latest master has the following issue for me.
```
content
   .push(Text::new("JPBbHU6B-3-T7Yz-AAAAAAAAAAA"))
   .push(Text::new("PBbHU6B-3-T7Yz-AAAAAAAAAAA"))
```
will show 
```
JPBbHU6B-3-T7Yz-
PBbHU6B-3-T7Yz-AAAAAAAAAAA
```

i.e. The first string sequence is only partially rendered. 
Removing the first char will allow it to print as normal.

**Comment by yusdacra** [comment] 2021-08-30 12:37
I noticed this also happens with emojis. Try putting an emoji at the start of a string, and it should be cut off.

**Comment by Kaiden42** [comment] 2021-08-30 12:48
Duplicate of #782

**Closed** 2021-08-31 19:13 UTC
Labels: duplicate
