### ISSUE TITLE
Can't build tour example for wasm32, pulling in net2 as dependency

### ISSUE THREAD

**Issue by tarkah** [hecrj/iced#145] opened 2020-01-06 23:05 UTC
When trying to build the tour example for wasm32 `cargo build --example tour --target wasm32-unknown-unknown`, I am getting a compilation error due to it trying to compile the `net2` library. This dependency appears to be pulled in by `window_clipboard` in `iced_winit`, which seems like a relatively recent addition. 

```
window_clipboard v0.1.0-alpha.2 (https://github.com/hecrj/window_clipboard?rev=22c6dd6c04cd05d528029b50a30c56417cd4bebf#22c6dd6c)
├── clipboard_wayland v0.1.0-alpha (https://github.com/hecrj/window_clipboard?rev=22c6dd6c04cd05d528029b50a30c56417cd4bebf#22c6dd6c)
│   └── smithay-clipboard v0.3.6
│       └── smithay-client-toolkit v0.6.4
│           ├── wayland-client v0.23.6
│           │   ├── calloop v0.4.4
│           │   │   ├── mio v0.6.21
│           │   │   │   ├── net2 v0.2.33
```

**Comment by hecrj** [comment] 2020-01-06 23:09
This is a duplicate of #142. I should add a note in the `iced_web` readme.

`window_clipboard` is only used in `iced_native`, though. The issue is most likely in a dev dependency, probably `async-std`.

**Comment by tarkah** [comment] 2020-01-06 23:17
Ahh, sorry for opening a duplicated issue. Thanks for the clarification. I'll wait for the 0.1.0 release.

**Comment by hecrj** [comment] 2020-01-06 23:22
No worries! Duplicate issues are fine!

There is a big native PR landing soon, I'll try to get `iced_web` up to speed soon after that!

**Comment by tarkah** [comment] 2020-01-06 23:25
Awesome! Thanks so much for your work on this crate. I really like the direction this project is going and can't wait to see where it goes.

**Closed** 2020-01-08 02:23 UTC
Labels: question
