### ISSUE TITLE
[Help wanted] Does iced support software rendering?

### ISSUE THREAD

**Issue by Hankszhang** [hecrj/iced#441] opened 2020-07-08 02:59 UTC
I'd like to use iced to build a native app, with requirement is to support some devices without graphics to render a video stream，does iced's renderer engine support software rendering?

**Comment by hecrj** [comment] 2020-07-08 03:19
It's not supported yet! This is a duplicate of #337, feel free to join the discussion there!

**Closed by hecrj** 2020-07-08 03:19 UTC
