### ISSUE TITLE
Support for text decoration

### ISSUE THREAD

**Issue by Checksum** [hecrj/iced#498] opened 2020-08-25 23:35 UTC
Is it possible to add text decoration like bold, italics, underline to certain widgets - say `Text` and `Button`? I'm mainly looking at using those to highlight certain parts in paragraph of text.

Hopefully I haven't missed anything in the docs that already facilitates this.

**Comment by hecrj** [comment] 2020-08-27 17:46
This is a duplicate of #156. I shared some of my thoughts there. Feel free to join the discussion!

**Closed by hecrj** 2020-08-27 17:46 UTC
Labels: duplicate
