### ISSUE TITLE
Scrollbar appears behind buttons + Broken 'explain UI' layout

### ISSUE THREAD

**Issue by rnd-ash** [hecrj/iced#821] opened 2021-04-08 14:54 UTC
To summaries, I've noticed that placing buttons in columns then putting columns into a scroll-view seems to lead to the scrollbar being forced behind the buttons, even though the columns and scrollbars both have padding and spacing.

![image](https://user-images.githubusercontent.com/14551965/114047975-0ad78900-9882-11eb-944f-1f735c82db92.png)

In the image above, you can see the scrollbar (Right) appears to be behind some buttons. 

Interestingly, with the UI wireframe enabled, it shows the UI is even more broken!
![image](https://user-images.githubusercontent.com/14551965/114048510-8d604880-9882-11eb-947b-51358fd889fd.png)

It appears like the wireframe for my custom table (Which is made out of buttons) is rendered correctly, but the wireframe for it is placed incorrectly at the bottom of the screen behind the Freeze frame data table at the bottom.

The code to generate a table of buttons is located here:
https://github.com/rnd-ash/OpenVehicleDiag/blob/main/app_rust/src/widgets/table.rs

The table emits a Message showing which x and y element was selected by the user

**Comment by 13r0ck** [comment] 2021-04-08 14:56
Dupe of #765

**Closed** 2021-05-04 06:03 UTC
