### ISSUE TITLE
Why are the fonts broken?

### ISSUE THREAD

**Issue by jakobneufeld** [hecrj/iced#1025] opened 2021-09-05 07:29 UTC
I am running arch linux, and the fonts are broken. I have tried looking through the source code, but no result. I am running the stopwatch example. Here is a screenshot. Do I have to install a font, to make it work?
![2021-09-05_09-25](https://user-images.githubusercontent.com/24791219/132119129-189bdcf6-46a2-4f67-b169-f96322cd992e.png)

**Comment by dhardy** [comment] 2021-09-05 08:29
Isn't this #1013?

**Comment by hecrj** [comment] 2021-09-07 11:46
I think your default system font may simply be missing latin glyphs. Given we have no font fallback strategy, this is what you will get in that case.

Thus, this is most likely a duplicate of #33.

**Closed by hecrj** 2021-09-07 11:46 UTC
