### ISSUE TITLE
tokio 1.0 is not updated for iced_futures 0.2

### ISSUE THREAD

**Issue by dancespiele** [hecrj/iced#713] opened 2021-01-23 02:26 UTC
I get this error:
```
thread 'tokio-runtime-worker' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/spielrs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.1.0/src/runtime/blocking/pool.rs:85:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

and that is because the crate of iced_furues 0.2 was released with the `tokio` version 0.3.6 https://crates.io/crates/iced_futures
a new release version with `tokio`  version 1.x is needed

**Comment by hecrj** [comment] 2021-01-24 00:04
Duplicate of #706.

**Closed by hecrj** 2021-01-24 00:04 UTC
Labels: duplicate
