### ISSUE TITLE
The example given in the README is not clear.

### ISSUE THREAD

**Issue by H-Logan** [hecrj/iced#531] opened 2020-09-17 19:08 UTC
The example given in the README does not run standalone, but it claims to be done.
>And that's everything! We just wrote a whole user interface. Iced is now able to:
>
>1. Take the result of our view logic and layout its widgets.
>2. Process events from our system and produce messages for our update logic.
>3. Draw the resulting user interface.

It's unclear because the README never actually covers how to _run_ the code provided, which makes it hard for new users to get started.

Also, the [same program](https://github.com/hecrj/iced/blob/master/examples/counter/src/main.rs) in the examples folder is written differently, and it doesn't compile until the following segment of code is removed.
```Rust
pub fn main() -> iced::Result {
              ^^^^^^^^^^^^^^^
```
```
cannot find type `Result` in crate `iced`
not found in `iced`rustc(E0412)
main.rs(3, 24): not found in `iced`
```

**Comment by arctic-alpaca** [comment] 2020-09-17 20:02
I hope I'm right to assume you use the version from crates.io, which is 0.1.1. To view the corresponding examples, you need to use the [0.1 branch](https://github.com/hecrj/iced/blob/0.1/examples/counter/src/main.rs). With those examples you should be able to get started.

**Comment by hecrj** [comment] 2020-09-18 02:08
This is a duplicate of #276 

The __overview__ in the `README` is meant to be a brief introduction to the concepts of the Elm Architecture. It is not a full example (it doesn't even have a main function!). It links to the API documentation and the examples at the end.

> Also, the same program in the examples folder is written differently, and it doesn't compile until the following segment of code is removed.

The main `README` and the examples `README` point this out:

> __Iced moves fast and the `master` branch can contain breaking changes!__ If you want to learn about a specific release, check out [the release list].

[the release list]: https://github.com/hecrj/iced/releases

**Closed** 2020-09-18 02:10 UTC
Labels: duplicate, question
